---
#
# Populates nodes with kubeconfig and ssh configuration for easier debugging
#

- name: ensure that .kube dir exists
  become: true
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/core/.kube
    - /root/.kube

- name: copy the kubeconfig to a node
  become: true
  copy:
    src: "{{playbook_dir}}/kubeconfig"
    dest: "{{ item }}"
  with_items:
    - /home/core/.kube/config
    - /root/.kube/config

- name: ensure that ssh dir exists
  become: true
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/core/.ssh
    - /root/.ssh

- name: copy authorized keys
  become: true
  copy:
    src: /home/core/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    remote_src: yes
    owner: root
    group: root

- name: copy private key to workload host
  become: true
  copy:
    src: "{{ansible_ssh_private_key_file}}"
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - /home/core/.ssh/id_rsa
    - /root/.ssh/id_rsa

- name: Permit root login
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "PermitRootLogin no"
    line: "PermitRootLogin yes"

- name: Restart sshd
  become: true
  systemd:
    name: sshd
    state: restarted
