---
#
# Install OCP 4.x playbook.
#

- hosts: orchestration
  user: "{{ ORCHESTRATION_USER | default('root') }}"
  roles:
    - role: cleanup
      when: (OPENSHIFT_AWS_INSTALL_CLEANUP | default(False) | bool) or (OPENSHIFT_LIBVIRT_INSTALL_CLEANUP | default(False) | bool)
    - role: install
      when: OPENSHIFT_INSTALL | default(True) | bool
    - role: quickstart
      when: OPENSHIFT_INSTALL | default(True) | bool
    - role: post-install
      when: OPENSHIFT_POST_INSTALL | default(False) | bool
    - role: post-config
      when: OPENSHIFT_TOOLING | default(False) | bool

- hosts: controller
  remote_user: "{{ OPENSHIFT_INSTALL_USER | default('core') }}"
  become: true
  roles:
    - role: controller-kickstart
      when: OPENSHIFT_DEBUG_TOOLING | default(False) | bool

- hosts: nodes
  remote_user: "{{ OPENSHIFT_INSTALL_USER | default('core') }}"
  become: true
  roles:
    - role: node-config
      when: OPENSHIFT_DEBUG_TOOLING | default(False) | bool
