---
#
# IPI install of OCP 4 on AWS
#

- name: Perform IPI install OCP 4 on AWS
  hosts: orchestration
  gather_facts: true
  remote_user: "{{orchestration_user}}"
  vars_files:
    - vars/install-on-aws.yml
  vars:
    platform: "aws"
  roles:
    - role: cleanup-on-aws
      when: openshift_cleanup|bool
    - role: install-on-aws
      when: openshift_install|bool
    - role: post-install
      when: openshift_post_install|bool
    - role: post-config-on-aws
      when: openshift_post_config|bool

- name: (Optional) Debugging configuration of workload node
  hosts: workload
  gather_facts: true
  remote_user: core
  vars_files:
    - vars/install-on-aws.yml
  roles:
    - role: node-debug-config
      when: openshift_debug_config|bool
  post_tasks:
    - name: Add other nodes to in-memory inventory
      when: openshift_debug_config|bool
      block:
        - name: Get master nodes
          shell: |
            oc get nodes -l 'node-role.kubernetes.io/master=' | awk 'NR>1 {print $1}'
          register: ocp_master_nodes

        - name: Get infra nodes
          shell: |
            oc get nodes -l 'node-role.kubernetes.io/infra=' | awk 'NR>1 {print $1}'
          register: ocp_infra_nodes

        - name: Get worker nodes
          shell: |
            oc get nodes -l 'node-role.kubernetes.io/worker=' | awk 'NR>1 {print $1}'
          register: ocp_worker_nodes

        - name: Add master nodes to in-memory inventory
          add_host:
            name: "{{ item }}"
            groups: master
            ansible_ssh_common_args: |-
              -o ProxyCommand='ssh -i {{ansible_private_key_file}} -W %h:%p core@{{inventory_hostname}}'
          with_items:
            - "{{ ocp_master_nodes.stdout_lines }}"

        - name: Add infra nodes to in-memory inventory
          add_host:
            name: "{{ item }}"
            groups: infra
            ansible_ssh_common_args: |-
              -o ProxyCommand='ssh -i {{ansible_private_key_file}} -W %h:%p core@{{inventory_hostname}}'
          with_items:
            - "{{ ocp_infra_nodes.stdout_lines }}"

        - name: Add worker nodes to in-memory inventory
          add_host:
            name: "{{ item }}"
            groups: worker
            ansible_ssh_common_args: |-
              -o ProxyCommand='ssh -i {{ansible_private_key_file}} -W %h:%p core@{{inventory_hostname}}'
          with_items:
            - "{{ ocp_worker_nodes.stdout_lines }}"

- name: (Optional) Debugging configuration of initially deployed nodes
  hosts: master, infra, worker
  gather_facts: true
  remote_user: core
  vars_files:
    - vars/install-on-aws.yml
  roles:
    - role: node-debug-config
      when: openshift_debug_config|bool
