---
#
# Adjusts the scale of a RHCOS cluster by spreading worker count across each availablity zone in a
# typical default cluster (4 availablity zones).
#

- name: Adjust the scale of a RHCOS cluster
  hosts: orchestration
  gather_facts: false
  remote_user: "{{orchestration_user}}"
  vars_files:
    - vars/scale.yml
  tasks:
    - name: Get cluster name
      shell: |
        {%raw%}oc get machineset -n openshift-machine-api -o=go-template='{{(index (index .items 0).metadata.labels {%endraw%} "{{rhcos_metadata_label_prefix}}/cluster-api-cluster" {%raw%})}}'{%endraw%}
      register: rhcos_cluster_name

    - name: Get cluster region
      shell: |
        {%raw%}oc get machineset -n openshift-machine-api -o=go-template='{{(index .items 0 ).spec.template.spec.providerSpec.value.placement.region }}'{%endraw%}
      register: rhcos_region

    - name: Set each machineset in each availability zone
      shell: |
        oc patch machineset {{rhcos_cluster_name.stdout}}-worker-{{rhcos_region.stdout}}{{item.ms}} --type=merge -n openshift-machine-api -p '{"spec": {"replicas": {{item.count|int}} }}'
      with_items:
        - ms: a
          count: "{{(rhcos_worker_count|int / 4) | round(0, 'ceil')}}"
        - ms: b
          count: "{{((rhcos_worker_count|int / 4) - 0.25) | round(0, 'ceil')}}"
        - ms: c
          count: "{{((rhcos_worker_count|int / 4) - 0.5) | round(0, 'ceil')}}"
        - ms: d
          count: "{{(rhcos_worker_count|int / 4) | round(0, 'floor')}}"

    - name: Poll node count to see if scaling finished
      shell: oc get nodes -l node-role.kubernetes.io/worker= --no-headers | grep " Ready" -c
      register: scaled_worker_node_count
      until: scaled_worker_node_count.stdout|int == rhcos_worker_count|int
      delay: 1
      retries: "{{poll_attempts|int}}"

    - name: Add additional label to worker nodes to provide ability to isolate workloads on workers
      shell: |
        oc label nodes --overwrite -l 'node-role.kubernetes.io/worker=' computenode=true
