---
# Get the DNS server addresses from OpenStack.
- name: Getting the IP address for the DNS VM ns-master
  shell: "{{ openstack }} server show ns-master.{{ clusterid }}.{{ dns_domain }} --format value -c addresses"
  register: dns_addresses
  changed_when: false

# Parse the IP address from the addresses output.
- name: Parsing the floating ip from the DNS VM addresses
  set_fact:
    # Example: dns-network=192.168.0.7, 172.21.0.112
    cluster_dns_ip: "{{ dns_addresses['stdout'].split(', ')[1] }}"
  failed_when: cluster_dns_ip == ""

# Read the DNS update key file.
- name: Reading the remote {{ dns_key_file }} file
  command: "grep secret {{ dns_key_file }}"
  register: update_secret
  changed_when: false

# Create a regular expression to get the secret key.
- name: Setting the regular expression to find the secret
  set_fact:
    # Example:        secret "8kjyy/xFvzapFwmcWwLzvA==";
    secret_regex: 'secret "(.*)";'

# Set the DNS secret value.
- name: Creating a variable with the DNS secret value
  set_fact:
    dns_key_secret: "{{ update_secret['stdout']|regex_findall(secret_regex)|first }}"
