---
#
# Populates nodes with kubeconfig and ssh configuration for easier debugging
#

- name: ensure that .kube dir exists
  become: true
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/core/.kube
    - /root/.kube

- name: copy the kubeconfig to a node
  become: true
  copy:
    src: "{{playbook_dir}}/kubeconfig"
    dest: "{{ item }}"
  with_items:
    - /home/core/.kube/config
    - /root/.kube/config
  when:
    - kubeconfig_auth_dir_path == ""

# handle case where kubeconfig is in another specified dir
- name: copy the kubeconfig to node from specific directory
  become: true
  copy:
    src: "{{ kubeconfig_auth_dir_path }}/auth/kubeconfig"
    dest: "{{ item }}"
  with_items:
    - /home/core/.kube/config
    - /root/.kube/config
  when:
    - kubeconfig_auth_dir_path != ""

- name: ensure that ssh dir exists
  become: true
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/core/.ssh
    - /root/.ssh

- name: copy authorized keys
  become: true
  copy:
    src: /home/core/.ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    remote_src: yes
    owner: root
    group: root

- name: copy private key to a node
  become: true
  copy:
    src: "{{ansible_ssh_private_key_file}}"
    dest: "{{ item }}"
    mode: 0600
  with_items:
    - /home/core/.ssh/id_rsa
    - /root/.ssh/id_rsa
