---
#
# Clean up Azure IPI install
#

- name: Check if a cluster is running
  stat:
    path: "{{ansible_user_dir}}/scale-ci-deploy/scale-ci-azure/metadata.json"
  register: cluster_status

- block:
    - name: Cleanup Azure cluster
      shell: |
        cd {{ansible_user_dir}}/scale-ci-deploy
        bin/openshift-install destroy cluster --log-level=debug --dir={{ansible_user_dir}}/scale-ci-deploy/scale-ci-azure/

    - name: Clean scale-ci-deploy openshift-install directories
      become: true
      file:
        path: "{{item}}"
        state: absent
      with_items:
        - "{{ansible_user_dir}}/scale-ci-deploy/bin"
        - "{{ansible_user_dir}}/scale-ci-deploy/scale-ci-azure"
  when: cluster_status.stat.exists == True
